import 'package:flutter/foundation.dart';
import 'package:speech_to_text/speech_recognition_result.dart';
import 'package:speech_to_text/speech_to_text.dart';

/// Handles initialization and listening with [SpeechToText].
class CommandHandler extends ChangeNotifier {
  final SpeechToText _speechToText = SpeechToText();
  bool _speechEnabled = false;
  String _lastWords = '';
  
  /// A map of String commands to their associated VoidCallback functions
  Map<String, VoidCallback> commands = {};
  
  /// Function to run when a command is matched
  Function(String)? onCommandMatched;

  CommandHandler() {
    _initSpeech();
  }

  /// Initialize the speech_to_text plugin.
  void _initSpeech() async {
    _speechEnabled = await _speechToText.initialize(
      onError: (val) => debugPrint('onSpeechError: $val'),
      onStatus: (val) => debugPrint('onSpeechStatus: $val'),
    );
    notifyListeners();
  }

  /// Starts a speech recognition session
  void startListening({String localeId = '', bool listenForMultipleOptions = false}) async {
    if (_speechEnabled && !_speechToText.isListening) {
      await _speechToText.listen(
        onResult: _onSpeechResult,
        localeId: localeId.isNotEmpty ? localeId : null,
        listenOptions: SpeechListenOptions(
          cancelOnError: true,
          partialResults: true,
          listenMode: ListenMode.dictation,
        ),
      );
      notifyListeners();
    }
  }

  /// Stops the active speech recognition session
  void stopListening() async {
    if (_speechToText.isListening) {
      await _speechToText.stop();
      notifyListeners();
    }
  }

  /// Callback generated by [SpeechToText] when a result is ready
  void _onSpeechResult(SpeechRecognitionResult result) {
    _lastWords = result.recognizedWords;
    _checkForCommand(_lastWords);
    notifyListeners();
  }
  
  /// Checks if the recognized text ends with any of the defined commands
  void _checkForCommand(String recognizedText) {
    final lowerCaseText = recognizedText.toLowerCase();
    
    // Check if the newly recognized text ends with any of our commands
    for (final commandEntry in commands.entries) {
      final command = commandEntry.key.toLowerCase();
      // We look at the very end of the recognized string, or if it exactly matches
      // A simple implementation: checking if the latest word(s) match the command.
      
      // Split the recognized text into words to check the last few words
      final words = lowerCaseText.split(RegExp(r'\s+'));
      final commandWords = command.split(RegExp(r'\s+'));
      
      if (words.length >= commandWords.length) {
        bool matches = true;
        for (int i = 0; i < commandWords.length; i++) {
            if (words[words.length - commandWords.length + i] != commandWords[i]) {
                matches = false;
                break;
            }
        }
        if (matches) {
           debugPrint('Command matched: $command');
           commandEntry.value.call();
           onCommandMatched?.call(commandEntry.key);
           
           // Optionally stop listening after a successful command, or keep listening
           // Let's reset the lastwords so we don't trigger it again immediately
           // You could also stop and restart to clear the buffer 
           // stopListening();
           return; // Prevent multiple triggers if commands share suffixes (though unlikely with whole words)
        }
      }
    }
  }

  bool get isListening => _speechToText.isListening;
  bool get hasSpeechError => _speechToText.hasError;
  bool get isSpeechEnabled => _speechEnabled;
  String get lastWords => _lastWords;
}
